app/home/forms.py
from flask_wtf import FlaskForm
from wtforms import (StringField, PasswordField, TextAreaField, FileField,
                     SubmitField)
from wtforms.validators import (InputRequired, ValidationError, EqualTo, Email,
                                Regexp)
from app.models import User
from flask import session


class RegisterForm(FlaskForm):
    '''会员注册'''
    name = StringField(
        label='昵称',
        validators=[InputRequired('请输入昵称！')],
        description='昵称',
        render_kw={
            'class': "form-control input-lg",
            'placeholder': "请输入昵称",
        })
    email = StringField(
        label='邮箱',
        validators=[InputRequired('请输入邮箱！'),
                    Email('邮箱格式不正确')],
        description='邮箱',
        render_kw={
            'class': "form-control input-lg",
            'placeholder': "请输入邮箱",
        })
    phone = StringField(
        label='手机',
        validators=[
            InputRequired('请输入手机！'),
            Regexp('^1[3|4|5|6|7|8][0-9]\d{4,8}$', message='手机格式不正确')
        ],
        description='手机',
        render_kw={
            'class': "form-control input-lg",
            'placeholder': "请输入手机",
        })
    pwd = PasswordField(
        label='密码',
        validators=[InputRequired('请输入密码！')],
        description='密码',
        render_kw={
            'class': "form-control input-lg",
            'placeholder': "请输入密码",
        })
    repwd = PasswordField(
        label='重复密码',
        validators=[
            InputRequired('请输入重复密码！'),
            EqualTo('pwd', message='两次密码不一致')
        ],
        description='重复密码',
        render_kw={
            'class': "form-control input-lg",
            'placeholder': "请输入重复密码",
        })

    def validate_name(self, field):
        name = field.data
        num = User.query.filter_by(name=name).count()
        if num == 1:
            raise ValidationError('昵称已经存在，请重新输入')

    def validate_email(self, field):
        email = field.data
        num = User.query.filter_by(email=email).count()
        if num == 1:
            raise ValidationError('邮箱已经存在，请重新输入')

    def validate_phone(self, field):
        phone = field.data
        num = User.query.filter_by(phone=phone).count()
        if num == 1:
            raise ValidationError('手机号已经存在，请重新输入')


class LoginFrom(FlaskForm):
    """会员登录表单"""
    name = StringField(
        label='账号',
        validators=[InputRequired('请输入账号！')],
        description='账号',
        render_kw={
            'class': "form-control input-lg",
            'placeholder': "请输入账号",
        })

    pwd = PasswordField(
        label='密码',
        validators=[InputRequired('请输入密码！')],
        description='密码',
        render_kw={
            'class': "form-control input-lg",
            'placeholder': "请输入密码",
        })

    def validate_name(self, field):
        """从Admin数据库中，检测账号是否存在，如果不存在则在account.errors中添加错误信息"""
        account = field.data
        num = User.query.filter_by(name=account).count()
        if num == 0:
            raise ValidationError('账号不存在')


class UserDetailForm(FlaskForm):
    name = StringField(
        label='昵称',
        validators=[InputRequired('请输入昵称！')],
        description='昵称',
        render_kw={
            'class': "form-control",
            'placeholder': "请输入昵称",
        })
    email = StringField(
        label='邮箱',
        validators=[InputRequired('请输入邮箱！'),
                    Email('邮箱格式不正确')],
        description='邮箱',
        render_kw={
            'class': "form-control",
            'placeholder': "请输入邮箱",
        })
    phone = StringField(
        label='手机',
        validators=[
            InputRequired('请输入手机！'),
            Regexp('^1[3|4|5|6|7|8][0-9]\d{4,8}$', message='手机格式不正确')
        ],
        description='手机',
        render_kw={
            'class': "form-control",
            'placeholder': "请输入手机",
        })
    face = FileField(
        label='头像',
        validators=[InputRequired('请上传头像')],
        description='头像',
        render_kw={'class': "form-control"})
    info = TextAreaField(
        label='简介',
        validators=[],
        description='简介',
        render_kw={
            'class': "form-control",
            'rows': "10",
        })


class PwdForm(FlaskForm):
    '''修改密码'''
    old_pwd = PasswordField(
        label='旧密码',
        validators=[InputRequired('请输入旧密码！')],
        description='旧密码',
        render_kw={
            'class': "form-control",
            'placeholder': "请输入旧密码",
        })
    new_pwd = PasswordField(
        label='新密码',
        validators=[InputRequired('请输入新密码！')],
        description='新密码',
        render_kw={
            'class': "form-control",
            'placeholder': "请输入新密码",
        })
    new_pwd_rep = PasswordField(
        label='确认密码',
        validators=[
            InputRequired('请再次输入新密码确认！'),
            EqualTo('new_pwd', message='两次密码不一致')
        ],
        description='再次输入新密码',
        render_kw={
            'class': "form-control",
            'placeholder': "再次输入新密码",
        })

    def validate_old_pwd(self, field):
        user = User.query.filter_by(name=session['login_user']).first()
        if not user.check_pwd(field.data):
            raise ValidationError('旧密码错误！')


class CommentForm(FlaskForm):
    content = TextAreaField(
        label='内容',
        validators=[InputRequired('请输入内容')],
        description='内容',
        render_kw={
            'class': "form-control",
            'rows': "5"
        })
    submit = SubmitField(
        label='提交评论', render_kw={
            "class": "btn btn-success",
            "id": "btn-sub"
        })

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

import app.home.views

app/home/views.py
import time
import json
import uuid
import datetime
from functools import wraps
from sqlalchemy import extract
from app.home import home
from app import db, fr
from flask import (render_template, redirect, url_for, flash, request, session,
                   Response)
from app.home.forms import (RegisterForm, LoginFrom, UserDetailForm, PwdForm,
                            CommentForm)
from app.models import User, Userlog, Comment, Moviecol, Preview, Movie, Tag
from app.commen import save_file, del_file


# 要求登录才能访问
def user_login_require(func):
    @wraps(func)
    def decorated_function(*args, **kwargs):
        if session.get('login_user', None) is None:
            # 如果session中未找到该键，则用户需要登录
            return redirect(url_for('home.login', next=request.path))
        return func(*args, **kwargs)

    return decorated_function


@home.route("/", methods=['GET'])
@home.route("/<int:page>/", methods=['GET'])
def index(page=None):
    page = 1 if page is None else page
    all_tag = Tag.query.all()
    # 星级转换
    star_list = [(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')]
    all_star = map(lambda x: {'num': x[0], 'info': x[1]}, star_list)
    # 年份列表
    now_year = time.localtime()[0]
    year_range = [year for year in range(int(now_year), int(now_year) - 5, -1)]
    # print(year_range)
    page_movies = Movie.query
    selected = dict()
    tag_id = request.args.get('tag_id', 0)  # 获取链接中的标签id，0为显示所有
    if int(tag_id) != 0:
        page_movies = page_movies.filter_by(tag_id=tag_id)
    selected['tag_id'] = tag_id

    star_num = request.args.get('star_num', 0)  # 获取星级数字，0为显示所有
    if int(star_num) != 0:
        page_movies = page_movies.filter_by(star=star_num)
    selected['star_num'] = int(star_num)

    time_year = request.args.get('time_year', 1)  # 1为所有日期，0为更早，月份为所选
    if int(time_year) == 0:
        page_movies = page_movies.filter(
            extract('year', Movie.release_time) < int(now_year) - 5)
    elif int(time_year) == 1:
        page_movies = page_movies  # 所有年份的电影
    else:
        page_movies = page_movies.filter(
            extract('year', Movie.release_time) == time_year)  # 筛选年份
    selected['time_year'] = time_year

    playnum = request.args.get('playnum', 1)  # 1为从高到低，0为从低到好
    if int(playnum) == 1:
        page_movies = page_movies.order_by(Movie.playnum.desc())
    else:
        page_movies = page_movies.order_by(Movie.playnum.asc())
    selected['playnum'] = playnum

    commentnum = request.args.get('commentnum', 1)  # 1为从高到低，0为从低到好
    if int(commentnum) == 1:
        page_movies = page_movies.order_by(Movie.commentnum.desc())
    else:
        page_movies = page_movies.order_by(Movie.commentnum.asc())
    selected['commentnum'] = commentnum

    page_movies = page_movies.paginate(page=page, per_page=12)
    return render_template(
        'home/index.html',
        all_tag=all_tag,
        all_star=all_star,
        now_year=now_year,
        year_range=year_range,
        selected=selected,
        page_movies=page_movies)


@home.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginFrom()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(name=data['name']).first()
        if not user.check_pwd(data['pwd']):
            flash('密码错误', category='error')
            return redirect(url_for('home.login'))
        session['login_user'] = user.name
        session['login_user_id'] = user.id
        userlog = Userlog(user_id=user.id, ip=request.remote_addr)
        db.session.add(userlog)
        db.session.commit()
        return redirect(url_for('home.user'))
    return render_template('home/login.html', form=form)


@home.route('/logout/')
def logout():
    session.pop('login_user', None)
    session.pop('login_user_id', None)
    return redirect(url_for('home.login'))


@home.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        data = form.data
        user = User(
            name=data['name'],
            email=data['email'],
            phone=data['phone'],
            uuid=uuid.uuid4().hex)
        user.set_pwd(form.pwd.data)
        db.session.add(user)
        db.session.commit()
        flash('注册成功', category='success')
        return redirect(url_for('home.login'))
    return render_template('home/register.html', form=form)


@home.route('/user/', methods=['GET', 'POST'])
@user_login_require
def user():
    login_user = User.query.get_or_404(int(session['login_user_id']))
    form = UserDetailForm(
        name=login_user.name,
        email=login_user.email,
        phone=login_user.phone,
        info=login_user.info)
    form.face.validators = []
    form.face.flags.required = False
    if form.validate_on_submit():
        # 上传文件
        if form.face.data:
            del_file(login_user.face, 'user')
            login_user.face = save_file(form.face.data, 'user')

        if login_user.name != form.name.data and User.query.filter_by(
                name=form.name.data).count() > 0:
            flash('昵称已经存在', 'error')
            return redirect(url_for('home.user'))
        login_user.name = form.name.data

        if login_user.email != form.email.data and User.query.filter_by(
                email=form.email.data).count() > 0:
            flash('昵称已经存在', 'error')
            return redirect(url_for('home.user'))
        login_user.email = form.email.data

        if login_user.phone != form.phone.data and User.query.filter_by(
                phone=form.phone.data).count() > 0:
            flash('昵称已经存在', 'error')
            return redirect(url_for('home.user'))
        login_user.phone = form.phone.data

        login_user.info = form.info.data
        db.session.commit()
        flash('修改资料成功', 'success')
        return redirect(url_for('home.user'))
    return render_template('home/user.html', form=form, login_user=login_user)


@home.route('/pwd/', methods=['GET', 'POST'])
@user_login_require
def pwd():
    form = PwdForm()
    if form.validate_on_submit():
        user = User.query.filter_by(name=session['login_user']).first_or_404()
        user.set_pwd(form.new_pwd.data)
        db.session.commit()
        flash('密码修改成功，请重新登录', category='success')
        return redirect(url_for('home.logout'))
    return render_template('home/pwd.html', form=form)


@home.route("/comments/", methods=['GET'])
@home.route("/comments/<int:page>/", methods=['GET'])
@user_login_require
def comments(page=None):
    page = 1 if page is None else page
    page_comments = Comment.query.filter_by(
        user_id=int(session['login_user_id'])).order_by(
            Comment.addtime.desc()).paginate(
                page=page, per_page=10)
    return render_template('home/comments.html', page_comments=page_comments)


@home.route("/userlog/", methods=['GET'])
@home.route("/userlog/<int:page>/", methods=['GET'])
@user_login_require
def userlog(page=None):
    page = 1 if page is None else page
    page_userlog = Userlog.query.filter_by(
        user_id=int(session['login_user_id'])).order_by(
            Userlog.addtime.desc()).paginate(
                page=page, per_page=10)
    return render_template('home/userlog.html', page_userlog=page_userlog)


@home.route("/moviecols/", methods=['GET'])
@home.route("/moviecols/<int:page>/", methods=['GET'])
@user_login_require
def moviecols(page=None):
    page = 1 if page is None else page
    page_moviecols = Moviecol.query.filter_by(
        user_id=int(session['login_user_id'])).order_by(
            Moviecol.addtime.desc()).paginate(
                page=page, per_page=10)
    return render_template(
        'home/moviecols.html', page_moviecols=page_moviecols)


@home.route('/moviecols/add/', methods=['GET', 'POST'])
@user_login_require
def add_moviecols():
    movie_id = request.args.get('movie_id', '')
    user_id = request.args.get('user_id', '')
    movie_collect = Moviecol.query.filter_by(
        user_id=int(user_id), movie_id=int(movie_id)).count()
    if movie_collect > 0:
        return json.dumps({'ok': 0})
    movie_collect = Moviecol(user_id=int(user_id), movie_id=int(movie_id))
    db.session.add(movie_collect)
    db.session.commit()
    return json.dumps({'ok': 0})


@home.route('/indexbanner/')
def indexbanner():
    previews = Preview.query.all()
    return render_template('home/indexbanner.html', previews=previews)


@home.route('/search/')
def search():
    keyword = request.args.get('keyword')
    search_movies = Movie.query.filter(
        Movie.title.ilike("%" + keyword + "%")).order_by(Movie.addtime.desc())
    search_count = Movie.query.filter(
        Movie.title.ilike("%" + keyword + "%")).count()
    return render_template(
        'home/search.html',
        keyword=keyword,
        search_movies=search_movies,
        search_count=search_count)


@home.route('/play/<int:movie_id>/', methods=['GET', 'POST'])
@home.route('/play/<int:movie_id>/page/<int:page>/', methods=['GET', 'POST'])
def play(movie_id, page=None):
    movie = Movie.query.join(Tag).filter(
        Tag.id == Movie.tag_id, Movie.id == int(movie_id)).first_or_404()
    if request.method == 'GET':
        movie.playnum += 1
        db.session.commit()
    form = CommentForm()
    if 'login_user' not in session:
        form.submit.render_kw = {
            'disabled': "disabled",
            "class": "btn btn-success",
            "id": "btn-sub"
        }
    if form.validate_on_submit() and 'login_user' in session:
        data = form.data
        comment = Comment(
            content=data['content'],
            movie_id=movie.id,
            user_id=session['login_user_id'])
        db.session.add(comment)
        movie.commentnum += 1
        db.session.commit()
        flash('评论成功', category='success')
        return redirect(url_for('home.play', movie_id=movie.id))
    page = 1 if page is None else page
    page_comments = Comment.query.join(Movie).join(User).filter(

app/templates/home/base.html
<!doctype html>
<html lang="zh-CN">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='base/images/logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/bootstrap-movie.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/animate.css') }}">
    <style>
        .navbar-brand>img {
            display: inline;
        }
    </style>
    <style>
        .media {
            padding: 3px;
            border: 1px solid #ccc
        }
    </style>
    {% block css %}{% endblock %}
</head>

<body>
    <!--导航-->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!--小屏幕导航按钮和logo-->
            <div class="navbar-header">
                <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="{{ url_for('home.index') }}" class="navbar-brand" style="width:250px;">
                    <img src="{{ url_for('static', filename='base/images/logo.png') }}" style="height:30px;">&nbsp;微电影
                </a>
            </div>
            <!--小屏幕导航按钮和logo-->
            <!--导航-->
            <div class="navbar-collapse collapse">
                <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                    <div class="form-group input-group">
                        <input type="text" class="form-control" placeholder="请输入电影名！" id="keyword" value="{{ keyword }}"
                                onkeydown="if(event.keyCode===13)return false;"
                        >
                        <span class="input-group-btn">
                            <a class="btn btn-default" id="do_search"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                        </span>
                    </div>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="curlink" href="{{ url_for('home.index') }}"><span class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                    </li>
                    <li>
                        <a class="curlink" href="{{ url_for('home.login') }}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                    </li>
                    <li>
                        <a class="curlink" href="{{ url_for('home.register') }}"><span class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                    </li>
                    <li>
                        <a class="curlink" href="{{ url_for('home.logout') }}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                    </li>
                    <li>
                        <a class="curlink" href="{{ url_for('home.user') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                    </li>
                </ul>
            </div>
            <!--导航-->

        </div>
    </nav>
    <!--导航-->
    {% block container %}
    <div class="container" style="margin-top:76px">
        {% block content %}{% endblock content %}
    </div>
    {% endblock container %}
    <!--内容-->
    <!--底部-->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p>
                        ©&nbsp;2018&nbsp;flaskmovie&nbsp;备案
                    </p>
                </div>
            </div>
        </div>
    </footer>
    <!--底部-->
    <script src="{{ url_for('static', filename='base/js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='base/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='base/js/jquery.singlePageNav.min.js') }}"></script>
    <script src="{{ url_for('static', filename='base/js/wow.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lazyload/jquery.lazyload.min.js') }}"></script>
    <script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
    <script>
        $(function () {
            new WOW().init();
        })

    </script>
    <script>
        $(document).ready(function () {
            $("img.lazy").lazyload({
                effect: "fadeIn"
            });
            $("#do_search").click(function () {
                let keyword = $('#keyword').val();
                location.href = "{{ url_for('home.search') }}?keyword=" + keyword;
            });
        });
    </script>
    {% block js %}{% endblock %}
</body>

</html>

app/templates/home/index.html
{% extends 'home/base.html' %}

{% block container %}
    <section id="hotmovie" style="margin-top:76px">
        <div class="container">
            <div class="row wow fadeInRight" data-wow-delay="0.6s">
                <div class="row">
                    <iframe class="wow fadeIn" width="100%" height="375px" frameborder=0 scrolling=no src="{{ url_for('home.indexbanner') }}"></iframe>
                </div>
            </div>
        </div>
    </section>
    <!--热门电影-->
    <!--电影列表-->
    <section id="movielist">
        <div class="container">
            <div class="row wow fadeIn" data-wow-delay="0.6s">
                <div class="col-md-12 table-responsive">
                    <table class="table text-left table-bordered" id="movietags">
                        <tr>
                            <td style="width:10%;">电影标签</td>
                            <td style="width:90%;">
                                <a class="label label-info" href="{{ url_for('home.index', page=1) }}?tag_id=0&star_num={{ selected['star_num'] }}&time_year={{ selected['time_year'] }}&playnum={{ selected['playnum'] }}&commentnum={{ selected['commentnum'] }}"><span class="glyphicon glyphicon-tag"></span>&nbsp;所有</a>
                                    &nbsp;
                                {% for tag in all_tag %}
                                    <a class="label label-info" href="{{ url_for('home.index', page=1) }}?tag_id={{ tag.id }}&star_num={{ selected['star_num'] }}&time_year={{ selected['time_year'] }}&playnum={{ selected['playnum'] }}&commentnum={{ selected['commentnum'] }}"><span class="glyphicon glyphicon-tag"></span>&nbsp;{{ tag.name }}</a>
                                    &nbsp;
                                {% endfor %}
                        </tr>
                        <tr>
                            <td>电影星级</td>
                            <td>
                                <a class="label label-warning" href="{{ url_for('home.index', page=1) }}?tag_id={{ selected['tag_id'] }}&star_num=0&time_year={{ selected['time_year'] }}&playnum={{ selected['playnum'] }}&commentnum={{ selected['commentnum'] }}"><span class="glyphicon glyphicon-star"></span>&nbsp;所有</a>
                                &nbsp;
                                {% for star in all_star %}
                                    <a class="label label-warning" href="{{ url_for('home.index', page=1) }}?tag_id={{ selected['tag_id'] }}&star_num={{ star.num }}&time_year={{ selected['time_year'] }}&playnum={{ selected['playnum'] }}&commentnum={{ selected['commentnum'] }}"><span class="glyphicon glyphicon-star"></span>&nbsp;{{ star.info }}</a>
                                    &nbsp;
                                {% endfor %}
                            </td>
                        </tr>
                        <tr>
                            <td>上映时间</td>
                            <td>
                                <a class="label label-default" href="{{ url_for('home.index', page=1) }}?tag_id={{ selected['tag_id'] }}&star_num={{ selected['star_num'] }}&time_year=1&playnum={{ selected['playnum'] }}&commentnum={{ selected['commentnum'] }}"><span class="glyphicon glyphicon-time">&nbsp;所有</span></a>
                                &nbsp;
                                {% for year in year_range %}
                                    <a class="label label-default" href="{{ url_for('home.index', page=1) }}?tag_id={{ selected['tag_id'] }}&star_num={{ selected['star_num'] }}&time_year={{ year }}&playnum={{ selected['playnum'] }}&commentnum={{ selected['commentnum'] }}"><span class="glyphicon glyphicon-time">&nbsp;{{ year }}</span></a>
                                    &nbsp;
                                {% endfor %}
                                <a class="label label-default" href="{{ url_for('home.index', page=1) }}?tag_id={{ selected['tag_id'] }}&star_num={{ selected['star_num'] }}&time_year=0&playnum={{ selected['playnum'] }}&commentnum={{ selected['commentnum'] }}"><span class="glyphicon glyphicon-time">&nbsp;更早</span></a>
                            </td>
                        </tr>
                        <tr>
                            <td>播放数量</td>
                            <td>
                                <a class="label label-success" href="{{ url_for('home.index', page=1) }}?tag_id={{ selected['tag_id'] }}&star_num={{ selected['star_num'] }}&time_year={{ selected['time_year'] }}&playnum=1&commentnum={{ selected['commentnum'] }}"><span class="glyphicon glyphicon-arrow-down">&nbsp;从高到底</span></a>
                                &nbsp;
                                <a class="label label-danger" href="{{ url_for('home.index', page=1) }}?tag_id={{ selected['tag_id'] }}&star_num={{ selected['star_num'] }}&time_year={{ selected['time_year'] }}&playnum=0&commentnum={{ selected['commentnum'] }}"><span class="glyphicon glyphicon-arrow-up">&nbsp;从低到高</span></a>
                            </td>
                        </tr>
                        <tr>
                            <td>评论数量</td>
                            <td>
                                <a class="label label-success" href="{{ url_for('home.index', page=1) }}?tag_id={{ selected['tag_id'] }}&star_num={{ selected['star_num'] }}&time_year={{ selected['time_year'] }}&playnum={{ selected['playnum'] }}&commentnum=1"><span class="glyphicon glyphicon-arrow-down">&nbsp;从高到底</span></a>
                                &nbsp;
                                <a class="label label-danger" href="{{ url_for('home.index', page=1) }}?tag_id={{ selected['tag_id'] }}&star_num={{ selected['star_num'] }}&time_year={{ selected['time_year'] }}&playnum={{ selected['playnum'] }}&commentnum=0"><span class="glyphicon glyphicon-arrow-up">&nbsp;从低到高</span></a>
                            </td>
                        </tr>
                    </table>
                </div>
                {% for movie in page_movies.items %}
                    <div class="col-md-3">
                        <div class="movielist text-center">
                            <!--<img data-original="holder.js/262x166"
                                        class="img-responsive lazy center-block" alt="">-->
                            <img src="{{ url_for('static', filename='movie/' + movie.logo) }}" class="img-responsive center-block" alt="" style="height: 180px; width: 260px">
                            <div class="text-left" style="margin-left:auto;margin-right:auto;width:210px;">
                                <span style="color:#999;font-style: italic;">{{ movie.title }}</span><br>
                                <div>
                                    {% for i in range(movie.star) %}
                                        <span class="glyphicon glyphicon-star" style="color:#FFD119"></span>
                                    {% endfor %}
                                    {% for i in range(5 - movie.star) %}
                                        <span class="glyphicon glyphicon-star-empty" style="color:#FFD119"></span>
                                    {% endfor %}
                                </div>
                            </div>
                            <a href="{{ url_for('home.play', movie_id=movie.id) }}" class="btn btn-primary" target="_blank" role="button"><span class="glyphicon glyphicon-play"></span>&nbsp;播放</a>
                        </div>
                    </div>
                {% endfor %}

                <div class="col-md-12">
                    <nav aria-label="Page navigation">
                        {% from "admin/_htmlhelpers.html" import render_pagination %}
                        {{ render_pagination(page_movies, 'home.index') }}
                    </nav>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

app/templates/home/usermenu.html
<div class="col-md-3">
    <div class="list-group">
        <a id="m-1" href="{{ url_for('home.user') }}" class="list-group-item">
            <span class="glyphicon glyphicon-user"></span>&nbsp;会员中心
        </a>
        <a id="m-2" href="{{ url_for('home.pwd') }}" class="list-group-item">
            <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
        </a>
        <a id="m-3" href="{{ url_for('home.comments') }}" class="list-group-item">
            <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
        </a>
        <a id="m-4" href="{{ url_for('home.userlog') }}" class="list-group-item">
            <span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
        </a>
        <a id="m-5" href="{{ url_for('home.moviecols') }}" class="list-group-item">
            <span class="glyphicon glyphicon-heart"></span>&nbsp;收藏电影
        </a>
    </div>
</div>